package com.jxfzzzt;

public class HelloWorld {
    public static void main(String[] args) {

        System.out.println("Hello JQF");
    }
}

/*


"D:\maven\edu\berkeley\cs\jqf\jqf-fuzz\2.0\jqf-fuzz-2.0.jar;D:\maven\com\pholser\junit-quickcheck-generators\1.0\junit-quickcheck-generators-1.0.jar;D:\maven\com\pholser\junit-quickcheck-core\1.0\junit-quickcheck-core-1.0.jar;D:\maven\org\javaruntype\javaruntype\1.3\javaruntype-1.3.jar;D:\maven\org\antlr\antlr-runtime\3.1.2\antlr-runtime-3.1.2.jar;D:\maven\ognl\ognl\3.1.12\ognl-3.1.12.jar;D:\maven\org\javassist\javassist\3.20.0-GA\javassist-3.20.0-GA.jar;D:\maven\ru\vyarus\generics-resolver\3.0.1\generics-resolver-3.0.1.jar;D:\maven\org\slf4j\slf4j-api\1.7.25\slf4j-api-1.7.25.jar;D:\maven\edu\berkeley\cs\jqf\jqf-instrument\2.0\jqf-instrument-2.0.jar;D:\maven\org\ow2\asm\asm\9.5\asm-9.5.jar;D:\maven\org\jacoco\org.jacoco.report\0.8.10\org.jacoco.report-0.8.10.jar;D:\maven\org\jacoco\org.jacoco.core\0.8.10\org.jacoco.core-0.8.10.jar;D:\maven\org\ow2\asm\asm-commons\9.5\asm-commons-9.5.jar;D:\maven\org\ow2\asm\asm-tree\9.5\asm-tree-9.5.jar;D:\maven\info\picocli\picocli\4.0.4\picocli-4.0.4.jar;D:\maven\org\eclipse\collections\eclipse-collections\10.4.0\eclipse-collections-10.4.0.jar;D:\maven\org\eclipse\collections\eclipse-collections-api\10.4.0\eclipse-collections-api-10.4.0.jar;D:\maven\junit\junit\4.13.1\junit-4.13.1.jar;D:\maven\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;D:\maven\org\projectlombok\lombok\1.18.28\lombok-1.18.28.jar;D:\maven\org\apache\commons\commons-compress\1.21\commons-compress-1.21.jar;D:\maven\org\apache\commons\commons-lang3\3.7\commons-lang3-3.7.jar;D:\maven\org\apache\commons\commons-math3\3.6.1\commons-math3-3.6.1.jar;D:\maven\org\apache\commons\commons-collections4\4.3\commons-collections4-4.3.jar"

-classpath "G:\java_projects\learn_JQF\target\classes;D:\maven\edu\berkeley\cs\jqf\jqf-fuzz\2.0\jqf-fuzz-2.0.jar;D:\maven\com\pholser\junit-quickcheck-generators\1.0\junit-quickcheck-generators-1.0.jar;D:\maven\com\pholser\junit-quickcheck-core\1.0\junit-quickcheck-core-1.0.jar;D:\maven\org\javaruntype\javaruntype\1.3\javaruntype-1.3.jar;D:\maven\org\antlr\antlr-runtime\3.1.2\antlr-runtime-3.1.2.jar;D:\maven\ognl\ognl\3.1.12\ognl-3.1.12.jar;D:\maven\org\javassist\javassist\3.20.0-GA\javassist-3.20.0-GA.jar;D:\maven\ru\vyarus\generics-resolver\3.0.1\generics-resolver-3.0.1.jar;D:\maven\org\slf4j\slf4j-api\1.7.25\slf4j-api-1.7.25.jar;D:\maven\edu\berkeley\cs\jqf\jqf-instrument\2.0\jqf-instrument-2.0.jar;D:\maven\org\ow2\asm\asm\9.5\asm-9.5.jar;D:\maven\org\jacoco\org.jacoco.report\0.8.10\org.jacoco.report-0.8.10.jar;D:\maven\org\jacoco\org.jacoco.core\0.8.10\org.jacoco.core-0.8.10.jar;D:\maven\org\ow2\asm\asm-commons\9.5\asm-commons-9.5.jar;D:\maven\org\ow2\asm\asm-tree\9.5\asm-tree-9.5.jar;D:\maven\info\picocli\picocli\4.0.4\picocli-4.0.4.jar;D:\maven\org\eclipse\collections\eclipse-collections\10.4.0\eclipse-collections-10.4.0.jar;D:\maven\org\eclipse\collections\eclipse-collections-api\10.4.0\eclipse-collections-api-10.4.0.jar;D:\maven\junit\junit\4.13.1\junit-4.13.1.jar;D:\maven\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;D:\maven\org\projectlombok\lombok\1.18.28\lombok-1.18.28.jar;D:\maven\org\apache\commons\commons-compress\1.21\commons-compress-1.21.jar;D:\maven\org\apache\commons\commons-lang3\3.7\commons-lang3-3.7.jar;D:\maven\org\apache\commons\commons-math3\3.6.1\commons-math3-3.6.1.jar;D:\maven\org\apache\commons\commons-collections4\4.3\commons-collections4-4.3.jar" com.intellij.rt.junit.JUnitStarter -ideVersion5 -junit4 com.jxfzzzt.JQFTest,testCopyAscii


 */